---
record: True
num_frames: 3
video_path: [training/videos/gg_matches]
bar_model_path: models/vision/bars/best.pt
csv_path: csv/
csv_fields:  ['time',
              'p1_name', 'p2_name',
              'p1_health', 'p2_health',
              'p1_tension', 'p2_tension',
              'p1_burst', 'p2_burst',
              'p1_risc', 'p2_risc',
              'p1_round_count', 'p2_round_count',
              'p1_counter', 'p2_counter',
              'p1_just', 'p2_just',
              'p1_punish', 'p2_punish',
              'p1_reversal', 'p2_reversal',
              'p1_curr_damaged', 'p2_curr_damaged',
              'p1_round_win', 'p1_set_win']
round_win_field: "p1_round_win"
set_win_field: "p1_set_win"
debug: False
use_round_start_image: True