---
record: True
num_frames: 3
video_path: [videos/evo/giovanna_ramlethal_1_nitro_redditto_lf1.mp4,
             videos/evo/asuka_ramlethal_1_zando_redditto_lsf1.mp4,
             videos/evo/chaos_giovanna_1_jack_nitro_wsf1.mp4,]
bar_model_path: models/vision/bars/best.pt
csv_path: videos/evo/data/temp
csv_fields:  ['time',
              'p1_name', 'p2_name',
              'p1_health', 'p2_health',
              'p1_tension', 'p2_tension',
              'p1_burst', 'p2_burst',
              'p1_risc', 'p2_risc',
              'p1_round_count', 'p2_round_count',
              'p1_counter', 'p2_counter',
              'p1_just', 'p2_just',
              'p1_punish', 'p2_punish',
              'p1_reversal', 'p2_reversal',
              'p1_curr_damaged', 'p2_curr_damaged',
              'p1_round_win', 'p1_set_win']
round_win_field: "p1_round_win"
set_win_field: "p1_set_win"
debug: True
use_round_start_image: False
tournament_mode: True
tournament_csv_fields: ["tournament", "set_time", "tournament_round", "p1_player_name", "p2_player_name", "round_index", "set_index"]
