---
record: False
num_frames: 6
video_path: videos/arcsys_world_tour/sol_nagoriyuki_1_umisho_verix_wsf1.mp4
bar_model_path: runs/detect/bar_batch3/weights/best.pt
pred_round_features: [
              'p1_health', 'p2_health',
              'p1_tension', 'p2_tension',
              'p1_burst', 'p2_burst',
              'p1_counter', 'p2_counter',
              'p1_curr_damaged', 'p2_curr_damaged']
pred_round_win_field: "p1_round_win"
pred_set_features: [
              'p1_burst', 'p2_burst',
              'p1_round_count', 'p2_round_count',]
pred_set_win_field: "p1_set_win"
round_model_path: notebooks/pipeline_round_mlp.pkl
set_model_path: notebooks/set_pipeline_mlp.pkl
